
#ifndef IOTYPES_H
#define IOTYPES_H

typedef enum { IO_TYPE_INPUT, IO_TYPE_OUTPUT, IO_TYPE_INPUT_OUTPUT } IOType;

typedef enum {
  IO_ADC_CHANNEL_01,
  IO_ADC_CHANNEL_02,
  IO_ADC_CHANNEL_03,
  IO_ADC_CHANNEL_04,
  IO_ADC_CHANNEL_05,
  IO_ADC_CHANNEL_06,
  IO_ADC_CHANNEL_07,
  IO_ADC_CHANNEL_08,
  IO_ADC_CHANNEL_09,
  IO_ADC_CHANNEL_10,
  IO_ADC_CHANNEL_11,
  IO_ADC_CHANNEL_12,
  IO_ADC_CHANNEL_13,
  IO_ADC_CHANNEL_14,
  IO_ADC_CHANNEL_15,
  IO_ADC_CHANNEL_16,
  IO_ADC_CHANNEL_17,
  IO_ADC_CHANNEL_18,
  IO_ADC_CHANNEL_19,
  IO_ADC_CHANNEL_20,
  IO_ADC_CHANNEL_MAX
} IOADCChannel_en;

typedef enum {
  IO_DAC_CHANNEL_01,
  IO_DAC_CHANNEL_02,
  IO_DAC_CHANNEL_MAX
} IODACChannel_en;

typedef enum { IO_HALL_CHANNEL_01, IO_HALL_CHANNEL_MAX } IOHallChannel;

typedef enum {
  IO_CAN_CHANNEL_01,
  IO_CAN_CHANNEL_02,
  IO_CAN_CHANNEL_03,
  IO_CAN_CHANNEL_MAX
} IOCANChannel_en;

typedef enum {
  IO_PWM_CHANNEL_01,
  IO_PWM_CHANNEL_02,
  IO_PWM_CHANNEL_03,
  IO_PWM_CHANNEL_04,
  IO_PWM_CHANNEL_05,
  IO_PWM_CHANNEL_06,
  IO_PWM_CHANNEL_MAX
} IOPWMChannel_en;

typedef enum {
  IO_DIN_CHANNEL_01,
  IO_DIN_CHANNEL_02,
  IO_DIN_CHANNEL_03,
  IO_DIN_CHANNEL_MAX
} IODINChannel_en;

typedef enum { IO_DOUT_CHANNEL_01, IO_DOUT_CHANNEL_MAX } IODOUTChannel;

typedef enum {
  IO_SPI_CHANNEL_01,
  IO_SPI_CHANNEL_02,
  IO_SPI_CHANNEL_03,
  IO_SPI_CHANNEL_MAX
} IOSPIChannel_en;

#endif // IOTYPES_H
